apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: workload-server-with-custom-ca
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
  name: workload-server-with-custom-ca
  namespace: jeremy
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "8"
  serviceClaims:
    - name: workload-server-with-custom-ca
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: workload-server-with-custom-ca
    - name: ca-cert
      ref:
        apiVersion: v1 
        kind: Secret
        name: tap-ca 
  params:
  # - name: buildServiceBindings
  #   value:
  #     - kind: Secret
  #       name: tap-ca
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      x95castle1.org/livenessProbe: '{"httpGet":{"path": "/actuator/health","port":8080},"initialDelaySeconds": 25,"periodSeconds": 5}'
      x95castle1.org/readinessProbe: '{"httpGet":{"path": "/actuator/health","port":8080},"initialDelaySeconds": 25,"periodSeconds": 5}'
  - name: scanning_source_policy
    value: lax-scan-policy
  - name: scanning_image_policy
    value: lax-scan-policy
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: test
  source:
    git:
      url: https://github.com/x95castle1/spring-rest-security-232.git
      ref:
        branch: main
